//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FahrtenbuchDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public System.Guid ID { get; set; }
        public System.Guid VehicleID { get; set; }
        public System.Guid EmployeeID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
